apiVersion: v1
kind: Service
metadata:
  name: redis
  labels: 
    name: redis-service
    app: demo-voting
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis
    app: demo-voting